//
//  CharactersInteractor.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 05/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class CharactersInteractor {
    var services : APIServicesInterfaces!
}

// MARK: - Extensions -

extension CharactersInteractor: CharactersInteractorInterface {
    
    convenience init(services: APIServicesInterfaces) {
        self.init()
        self.services = services
    }
    
    func fetchCharacters() -> Driver<[Character]> {
        return services.fetchCharacters()
    }
}
