//
//  MainViewController.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 05/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxCocoa
import RxSwift

final class MainViewController: UIViewController {

    // MARK: - Public properties -
    @IBOutlet private weak var tableView : UITableView!
    private var disposeBag = DisposeBag()
    private let sections = ["Episodes","Characters"]

    var presenter: MainPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Menu"
        
        tableView
        .rx
        .modelSelected(String.self)
        .subscribe { _ in
            let index = self.tableView.indexPathForSelectedRow?.row ?? 0
            self.displaySection(index: index)
        }.disposed(by: disposeBag)
        
        BehaviorRelay.init(value: sections).bind(to: tableView.rx.items(cellIdentifier: "mainCell")){ row, item, cell in
            cell.textLabel?.text = item
        }.disposed(by: disposeBag)
    }
}


// MARK: - Extensions -

extension MainViewController: MainViewInterface {
    func displaySection(index : Int){
        presenter.gotoSection(index : index)
    }
}
