//
//  MainInterfaces.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 05/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MainWireframeInterface: WireframeInterface {
    func pushToSectionEpisodes()
    func pushToSectionCharacters()
}

protocol MainViewInterface: ViewInterface {
    func displaySection(index : Int)
}

protocol MainPresenterInterface: PresenterInterface {
    func gotoSection(index: Int)
}
