//
//  CharacterDetailWireframe.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 04/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CharacterDetailWireframe: BaseWireframe<CharacterDetailViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "CharacterDetail", bundle: nil)

    // MARK: - Module setup -

    init(character : Character) {
        let moduleViewController = storyboard.instantiateViewController(withIdentifier: "CharacterDetailViewController") as! CharacterDetailViewController
        super.init(viewController: moduleViewController)

        let interactor = CharacterDetailInteractor(services: ApiService.getInstance())
        let presenter = CharacterDetailPresenter(character: character, view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CharacterDetailWireframe: CharacterDetailWireframeInterface {
    func pushEpisodeDetail(episode: Episode) {
        navigationController?.pushWireframe(EpisodeDetailWireframe(episode: episode))
    }
    
}
