//
//  CharacterDetailViewController.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 04/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

final class CharacterDetailViewController: UIViewController {
    
    @IBOutlet private weak var name: UILabel!
    @IBOutlet private weak var origin: UILabel!
    @IBOutlet private weak var species: UILabel!
    @IBOutlet private weak var planet: UILabel!
    @IBOutlet private weak var avatar: UIImageView!
    @IBOutlet private weak var tableView: UITableView!
    private let disposeBag = DisposeBag()
    
    // MARK: - Public properties -

    var presenter: CharacterDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Character's Detail"
        
        presenter.character.asObservable().bind {
            self.name.text = $0.name
            self.origin.text = $0.origin.name
            self.species.text = $0.species
            self.planet.text = $0.location.name
            self.avatar.setUrlImage(url: $0.image)
        }.disposed(by: disposeBag)
        
        presenter.fillEpisodes()
        
        presenter.episodes.bind(to: tableView.rx.items(cellIdentifier: "episodeCell")){ row, item, cell in
            cell.textLabel?.text = item.name
        }
        .disposed(by: disposeBag)
        
        tableView
            .rx
            .modelSelected(Episode.self)
            .subscribe({_ in
                let index = self.tableView.indexPathForSelectedRow?.row ?? 0
                self.displayEpisodeDetail(index: index)
            })
            .disposed(by:disposeBag)
    }

}

// MARK: - Extensions -

extension CharacterDetailViewController: CharacterDetailViewInterface {
    func displayEpisodeDetail(index : Int){
        presenter.gotoEpisodeDetail(index: index)
    }
}
