//
//  EpisodeDetailInterfaces.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 03/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxCocoa

protocol EpisodeDetailWireframeInterface: WireframeInterface {
    func pushCharacterDetail(character : Character)
}

protocol EpisodeDetailViewInterface: ViewInterface {
    func displayCharacterDetail(index : Int)
}

protocol EpisodeDetailPresenterInterface: PresenterInterface {
    var episode: BehaviorRelay<Episode> { get }
    var characters: BehaviorRelay<[Character]> { get }
    
    func fillCharacters()
    
    func goToCharacterDetail(index: Int)
}

protocol EpisodeDetailInteractorInterface: InteractorInterface {
    func fetchCharacter(_ url : String) -> Driver<Character>
}
