//
//  EpisodesViewController.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 03/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

final class EpisodesViewController: UIViewController {
    
    @IBOutlet private weak var tableView: UITableView!
    private let disposeBag = DisposeBag()
    
    // MARK: - Public properties -

    var presenter: EpisodesPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Episodes"
        
        presenter.getEpisodes()

        tableView.rx
        .modelSelected(Episode.self)
        .subscribe ({ (_) in
            let index = self.tableView.indexPathForSelectedRow?.row ?? 0
            self.displayEpisodeDetail(index: index)
        }).disposed(by: disposeBag)

        presenter.episodes.bind(to: tableView.rx.items(cellIdentifier: "episodeCell")) {
            row, item, cell in
            cell.textLabel?.text = item.name
        }.disposed(by: disposeBag)
        
    }
}

// MARK: - Extensions -

extension EpisodesViewController: EpisodesViewInterface {

    func displayEpisodeDetail(index: Int) {
        presenter.goToDetail(index: index)
    }
}
