//
//  EpisodesInterfaces.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 03/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxCocoa

protocol EpisodesWireframeInterface: WireframeInterface {
    func pushEpisodeDetail(episode : Episode)
}

protocol EpisodesViewInterface: ViewInterface {
    func displayEpisodeDetail(index: Int)
}

protocol EpisodesPresenterInterface: PresenterInterface {
    
    var episodes: BehaviorRelay<[Episode]> { get }
    
    func getEpisodes()
    
    func goToDetail(index: Int)
}

protocol EpisodesInteractorInterface: InteractorInterface {
    func fetchEpisodes() -> Driver<[Episode]>
}
