//
//  EpisodesWireframe.swift
//  RickAndMorty
//
//  Created by Patrick VONGPRASEUTH on 03/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EpisodesWireframe: BaseWireframe<EpisodesViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Episodes", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(withIdentifier: "EpisodesViewController") as! EpisodesViewController
        super.init(viewController: moduleViewController )

        let interactor = EpisodesInteractor(services: ApiService.getInstance())
        let presenter = EpisodesPresenter(view: moduleViewController as EpisodesViewInterface, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension EpisodesWireframe: EpisodesWireframeInterface {
    
    func pushEpisodeDetail(episode: Episode) {
        navigationController?.pushWireframe(EpisodeDetailWireframe(episode: episode))
    }
}
